on:
  push:
    branches:
      - master
      - deploy
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'
      - name: dockerize
        run: docker build -t local-image -f ./Dockerfile .
      - name: tag docker images
        run: |
          docker tag local-image 'towli/radio-backend:${GITHUB_SHA::8}'
      - name: push image to ecr
        uses: kciter/aws-ecr-action@v1
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: docker/radio-backend
          region: us-east-1
          tags: latest,${GITHUB_SHA::8}
          create_repo: true
    cdk:
      steps:
        - name: cdk diff
          uses: youyo/aws-cdk-github-actions@v1
          with:
            cdk_subcommand: 'diff'
            actions_comment: true
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: 'us-east-1'

        - name: cdk deploy
          uses: youyo/aws-cdk-github-actions@v1
          with:
            cdk_subcommand: 'deploy'
            cdk_stack: 'stack1'
            actions_comment: false
            args: '--require-approval never'
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: 'us-east-1'

        - name: cdk synth
          uses: youyo/aws-cdk-github-actions@v1
          with:
            cdk_subcommand: 'synth'
            cdk_version: '1.16.2'
            working_dir: 'src'
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: 'us-east-1'
